---
abstract: 'A fully event driven IRC Services module'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: POE::Component::IRC::Service
name: POE-Component-IRC-Service
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  Carp: 0
  POE: 0.0607
  Socket: 0
version: 0.994
